### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by amal-khailtash** [cjdrake/AES#6]
Hi Chris.  Sorry, I could not find your contact information.  What is the licensing for "aes.c" code?  I see "Copyright (c) 2013, Intel Corporation, All rights reserved" at the top of the file.  Do you know what the source and licensing is for the C code?

**Comment by cjdrake** [comment]
The repo is BSD 2-clause, which covers all source files. I'm pretty sure that as long as you retain the provenance info, you can use it for whatever you want.

**Comment by amal-khailtash** [comment]
BSD 2-clause only covers redistribution.  What about modification to the source code?  All of these are your implementation and how does it relate to Intel?

**Comment by cjdrake** [comment]
"Redistribution and use in source and binary forms, with or without
modification,"

So you can use and modify it, and do whatever.

The Intel/Google copyrights are due to the fact that I worked at Intel/Google when I wrote this stuff, and they were paying the EDA tool license costs. So I had to ask permission to publish as open source. Intel asked me to add the DISCLAIMER file, which says this is all just academic.
